services:
  - type: web
    name: neonai-bots
    runtime: node
    rootDir: discord
    buildCommand: npm install
    startCommand: npm run cloud-bots
    plan: free
    healthCheckPath: /
    buildFilter:
      paths:
        - discord/**
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_TICKET_BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: NEONAI_WEBSITE_URL
        value: https://neonai-official.netlify.app
